Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,22 +1,27 @@
-name: Automated Test
-
+name: Test Cases
 on: [push]
-
 jobs:
-  automated_test:
-    name: Automated Test
+  test_cases:
+    name: Test Cases
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - name: Set up Python 3.10
-        uses: actions/setup-python@v4
+      - uses: actions/checkout@v4
+      - name: Setup Python 3.10
+        uses: actions/setup-python@v3
         with:
           python-version: "3.10"
-      - name: Run Tests
+      
+      - name: Run tests
         run: |
-          python find_lowest_number.py test_data/test1_input.txt output1.txt
-          diff output1.txt test_data/test1_expected.txt
-          python find_lowest_number.py test_data/test2_input.txt output2.txt
-          diff output2.txt test_data/test2_expected.txt
-          python find_lowest_number.py test_data/test3_input.txt output3.txt
-          diff output3.txt test_data/test3_expected.txt
+                  python3 find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
+                  python3 find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
+                  python3 find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
+
+      - name: Compare the output 
+        run: |
+                  diff -Z test_data/test1_output.txt test_data/test1_expected.txt || echo "Test 1 failed!"
+                  diff -Z test_data/test2_output.txt test_data/test2_expected.txt || echo "Test 2 failed!"
+                  diff -Z test_data/test3_output.txt test_data/test3_expected.txt || echo "Test 3 failed!"
+
+
+
